apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorerdb.mynetwork.com
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorerdb.mynetwork.com
      
  template:
    metadata:
      labels:
        app: explorerdb.mynetwork.com
        
    spec:
      networks:
        mynetwork.com:
          external:
            name: net_byfn
      volumes:
      - name: data
        emptyDir: {}
      - name: pgdata
        emptyDir: {}
      - name: config
        configMap:
          name: hlf-scripts
          
      containers:
      - name: postgres
        image: postgres:10-alpine
        ports:
          - containerPort: 5432
        
        hostname: explorerdb.mynetwork.com
        command: ["sh" , "-c" , "mkdir -p /fabric/config/explorer/db/ && mkdir -p /fabric/config/explorer/app/ && cd /fabric/config/explorer/db/ && \
          wget https://raw.githubusercontent.com/hyperledger/blockchain-explorer/master/app/persistence/fabric/postgreSQL/db/createdb.sh && \
          wget https://raw.githubusercontent.com/hyperledger/blockchain-explorer/master/app/persistence/fabric/postgreSQL/db/explorerpg.sql && \
          wget https://raw.githubusercontent.com/hyperledger/blockchain-explorer/master/app/persistence/fabric/postgreSQL/db/processenv.js && \
          wget https://raw.githubusercontent.com/hyperledger/blockchain-explorer/master/app/persistence/fabric/postgreSQL/db/updatepg.sql && \
          apk update && \
          apk add jq && \
          apk add nodejs && \
          apk add sudo && \
          rm -rf /var/cache/apk/* && \
          chmod +x ./createdb.sh && \
          apk add postgresql-9.1 && \
          ln -s /tmp/.s.PGSQL.5432 /var/run/postgresql/.s.PGSQL.5432 && \
          ./createdb.sh"]
        env:
          - name: TZ
            value: "Asia/Singapore"
          - name: DATABASE_DATABASE
            value: fabricexplorer
          - name: DATABASE_USERNAME
            value: hppoc
          - name: DATABASE_PASSWD
            value: password
        
  
          
        volumeMounts:
        - name: config
          mountPath: /docker-entrypoint-initdb.d/createdb.sh
          subPath: createdb.sh
        - name: pgdata
          mountPath: /var/lib/postgresql/data
         
       ## ports:
       ## - name: http
       ##  containerPort: 5432
       ##   protocol: TCP
      
     
